name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Build container-diff
        run: |
          make
          ./out/container-diff version

      - name: Install addlicense
        run: go install github.com/google/addlicense@v1.1.1

      - name: Run tests
        run: make test

      - name: Run integration tests
        run: make integration

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: latest
          install-only: true

      - name: Build snapshot
        run: |
          make snapshot
          ./dist/container-diff-build_linux_amd64_v1/container-diff version
